#!/usr/bin/env python3

import amulet
import requests
import unittest

seconds = 900


class TestDeployment(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.deployment = amulet.Deployment()

        cls.deployment.add('nginx-proxy')
        cls.deployment.expose('nginx-proxy')

        try:
            cls.deployment.setup(timeout=seconds)
            cls.deployment.sentry.wait()
        except amulet.helpers.TimeoutError:
            message = 'Environment did not setup in {0} seconds.'.format(seconds)
            amulet.raise_status(amulet.SKIP, msg=message)
        except:
            raise
        cls.unit = cls.deployment.sentry.unit['nginx-proxy/0']

    def test_case(self):
        """
        Without a proxy relationship this charm should just serve the default
        nginx page.  Check for that and raise an error if it is not available.
        """
        address = self.unit.info['public-address']
        response = requests.get('http://{0}'.format(address))
        response.raise_for_status()

        print("more website tests go here")
        pass


if __name__ == '__main__':
    unittest.main()
