#!/usr/bin/python

import consultemplate
import os
import sys

from charmhelpers.core import hookenv

hooks = hookenv.Hooks()
log = hookenv.log


@hooks.hook('config-changed')
def config_changed():
    config = hookenv.config()

    service_name = config['service-name']
    hookenv.log('service-name: {0}'.format(service_name))

    hookenv.log('Reading {0}'.format(consultemplate.ORIGINAL_CTMPL))
    with open(consultemplate.ORIGINAL_CTMPL) as stream:
        contents = stream.read()
    new_contents = contents.replace('juju-service-name', service_name)
    if os.path.isfile(consultemplate.MANAGED_CTMPL):
        hookenv.log('Reading {0}'.format(consultemplate.MANAGED_CTMPL))
        with open(consultemplate.MANAGED_CTMPL) as stream:
            current = stream.read()
        changed = new_contents != current
    else:
        changed = True
    if changed:
        hookenv.log('juju-service-name value changed.')
        hookenv.log('Writing {0}'.format(consultemplate.MANAGED_CTMPL))
        with open(consultemplate.MANAGED_CTMPL, 'w') as stream:
            stream.write(new_contents)
    # Start or reload the consul-template service.
    consultemplate.ensure_consul_template_running(changed)


if __name__ == "__main__":
    # execute a hook based on the name the program is called by
    hooks.execute(sys.argv)
