#!/usr/bin/python

import setup
setup.pre_install()

import sys
import consultemplate

from charmhelpers import fetch
from charmhelpers.core import hookenv

hooks = hookenv.Hooks()


@hooks.hook('install')
def install():
    hookenv.log('Installing nginx')
    fetch.apt_install(fetch.filter_installed_packages(['nginx']))
    hookenv.log('Installing consul-template')
    consultemplate.install_consul_template()
    hookenv.log('Install complete.')


if __name__ == "__main__":
    hooks.execute(sys.argv)
