#!/usr/bin/python

import sys

from charmhelpers.core import (
    hookenv,
    host,
)

hooks = hookenv.Hooks()


@hooks.hook('start')
def start():
    for service in ['consul-template', 'nginx']:
        hookenv.log('Starting {0}'.format(service))
        host.service_restart(service) or host.service_start(service)
    hookenv.open_port(80)


if __name__ == '__main__':
    # execute a hook based on the name the program is called by
    hooks.execute(sys.argv)
